### PR TITLE
Setting up the project

### PR DESCRIPTION
**Pull request by KalinGv**
The script from app.bundle.js can't be run form calc.html

### CODE REVIEW

**Comment by KalinGv** [comment]
Can you check my pull requests when you have time

**Comment by mgenov** [comment]
will check it in few minutes.

**Comment by mgenov** [comment]
image

Got this error. Looks like a dependency issue.

**Comment by KalinGv** [comment]
when this error happens ?

**Comment by KalinGv** [comment]
i think i updated babel

**Comment by KalinGv** [comment]
but the bundle still can't be used as a script file

**Comment by mgenov** [comment]
Yes, it's related to babel.

**Comment by KalinGv** [comment]
ok

**Comment by mgenov** [comment]
I'm looking into it right now. Will comment when I get some results.

**Comment by KalinGv** [comment]
thank you, i'll also try to search for some information about how to solve the problem

**Comment by mgenov** [comment]
Will merge this PR and will file up a new one with changes.

**Comment by KalinGv** [comment]
ok

**Pull request merged**
